export const ROUTES = {
  HOME: '/',
  PRODUCTS: '/products',
  PRODUCT_DETAIL: (slug: string) => `/products/${slug}`,
  CATEGORIES: '/categories',
  CATEGORY_DETAIL: (slug: string) => `/categories/${slug}`,
  SEARCH: '/search',
  CART: '/cart',
  CHECKOUT: '/checkout',
  
  CUSTOMER: {
    LOGIN: '/customer/login',
    REGISTER: '/customer/register',
    ACCOUNT: '/customer/account',
    ORDERS: '/customer/orders',
    ORDER_DETAIL: (id: string) => `/customer/orders/${id}`,
    WISHLIST: '/customer/wishlist',
    ADDRESSES: '/customer/addresses',
  },
  
  SELLER: {
    LOGIN: '/seller/login',
    REGISTER: '/seller/register',
    DASHBOARD: '/seller/dashboard',
    PRODUCTS: '/seller/products',
    NEW_PRODUCT: '/seller/products/new',
    EDIT_PRODUCT: (id: string) => `/seller/products/${id}`,
    INVENTORY: '/seller/inventory',
    ORDERS: '/seller/orders',
    RETURNS: '/seller/returns',
    EARNINGS: '/seller/earnings',
    PAYOUTS: '/seller/payouts',
    SETTINGS: '/seller/settings',
  },
  
  ADMIN: {
    LOGIN: '/admin/login',
    DASHBOARD: '/admin/dashboard',
    USERS: '/admin/users',
    SELLERS: '/admin/sellers',
    PRODUCTS: '/admin/products',
    CATEGORIES: '/admin/categories',
    ORDERS: '/admin/orders',
    PAYMENTS: '/admin/payments',
    COMMISSIONS: '/admin/commissions',
    PAYOUTS: '/admin/payouts',
    RETURNS: '/admin/returns',
    COUPONS: '/admin/coupons',
    REVIEWS: '/admin/reviews',
    INVENTORY: '/admin/inventory',
    REPORTS: '/admin/reports',
    SETTINGS: '/admin/settings',
  },
};
